apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.14.3
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
